### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by huaibovip** [MungoMeng/Registration-CorrMLP#1]
期待作者尽快上传代码

**Comment by yidamyth** [comment]
请问去哪儿下载原文哇

**Comment by MungoMeng** [comment]
谢谢对我们工作的关注！全文和代码都会在cvpr会议之前上传到github和arxiv。

**Comment by yidamyth** [comment]
> github

好的，谢谢学长您的回复，一直在网上找不到原文，以为自己的查找出错了。

**Comment by MungoMeng** [comment]
论文原文目前已经上传到arXiv: https://arxiv.org/abs/2406.00123

**Comment by yidamyth** [comment]
> 

感谢学长。

**Comment by MungoMeng** [comment]
@huaibovip 代码已上传，谢谢对我们工作的关注！
