### ISSUE TITLE
Paper

### ISSUE THREAD

**Issue by MedAIerHHL** [MungoMeng/Registration-CorrMLP#2]
Congrats！Can you share the paper on arxiv or anywhere? It would be better if there was a Chinese version. Thanks!

**Comment by MungoMeng** [comment]
Thanks for your interest in our work! We will release both the code and paper very soon -- no later than the CVPR conference.

**Comment by MungoMeng** [comment]
The paper is available at https://arxiv.org/abs/2406.00123.
